name = "FWFTables"
uuid = "1acc1471-1fd5-4be2-a8c2-3f3b1db75813"
authors = ["henrico "]
version = "0.1.0"

[deps]
FixedSizeStrings = "3ca710bb-85d4-534c-9bae-b7b5d9e27e20"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
FixedSizeStrings = "0.1"
Formatting = "0.4"
Parsers = "1.0"
Tables = "1.0"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
